#! /bin/bash
docker rm databasecontainer -f
docker rmi database:latest
docker build -t database:latest .
eval "docker run --name databasecontainer -p 27017:27017 --network host -e MONGO-INITDB-DATABASE=maindatabase database"
